### ISSUE TITLE
Character Animations and General Polish

### ISSUE THREAD

**Issue by Rud156** [Rud156/ShooterGame#7]
This is a Global Task that will get updated once each character gets completed

# To-do

- [x]  Implement a Fixed tick without the use of FixedUpdate
- [x]  Add some sort of acceleration to the player movement. Like when the button for move is pressed it takes a very short duration of get up to full speed
- [x]  ~Change health to be 1 or 2 point float instead of int~
- [x]  Implement Shader damage and flash effect for when players take damage
- [x]  Update the game and everything to use the color pallet described
- [x]  Implement World UI for Enemies and Players
    - [x]  Health
    - [x]  Damage
- [x] Change Ultimate System to Point Based system like OW 
- [x]  Hunter
- [x]  Aqua
- [x]  Nightfall
    - [x]  ~~Update Type 4 (Nightfall) Fall Float to use an ability instead~~
- [x]  Rocket
- [x]  Spark (Definitely needs a color change)
